-- ============================================================
-- DROP COLUMN: Hapus kolom `kualitas` dari tabel tidur
-- Generated by Nerobot — 2026-08-10
-- ============================================================

ALTER TABLE public.tidur DROP COLUMN IF EXISTS kualitas;
