-- ============================================================
-- Allow tasks to be saved WITHOUT a date (for "ide yang belum matang")
-- Generated by Nerobot — 2026-08-12
-- ============================================================

ALTER TABLE public.tasks ALTER COLUMN tanggal DROP NOT NULL;

-- Selesai! 🐱
