-- ============================================================
-- ADD COLUMN: goal.is_utama (boolean, hanya 1 goal yg TRUE per user)
-- Generated by Nerobot — 2026-08-15
-- ============================================================

ALTER TABLE public.goal ADD COLUMN IF NOT EXISTS is_utama BOOLEAN NOT NULL DEFAULT false;

-- Selesai! 🐱
