-- ============================================================
-- SWOT: dukung banyak analisis (multi-topic)
-- Generated by Nerobot — 2026-08-16
--   swot_topics : 1 baris = 1 analisis/subjek
--   swot_items  : ditambah topic_id (tiap poin milik 1 analisis)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.swot_topics (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    judul TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_swot_topics_user ON public.swot_topics(user_id);

ALTER TABLE public.swot_items
    ADD COLUMN IF NOT EXISTS topic_id UUID REFERENCES public.swot_topics(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_swot_items_topic ON public.swot_items(topic_id);

-- Migrasi data lama: buat 1 topik "Analisis Umum" per user, pindahkan item tanpa topik ke sana
INSERT INTO public.swot_topics (user_id, judul)
SELECT DISTINCT user_id, 'Analisis Umum'
FROM public.swot_items
WHERE topic_id IS NULL;

UPDATE public.swot_items s
SET topic_id = t.id
FROM public.swot_topics t
WHERE s.topic_id IS NULL
  AND s.user_id = t.user_id
  AND t.judul = 'Analisis Umum';

-- RLS
ALTER TABLE public.swot_topics ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own swot_topics" ON public.swot_topics;
CREATE POLICY "Users can CRUD own swot_topics" ON public.swot_topics
    FOR ALL USING (auth.uid() = user_id);

-- Trigger updated_at
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'swot_topics_updated_at') THEN
        CREATE TRIGGER swot_topics_updated_at BEFORE UPDATE ON public.swot_topics
            FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
    END IF;
END
$$;

-- Realtime
DO $$
BEGIN
    BEGIN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.swot_topics';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END
$$;

-- Selesai! 🐱
