-- ============================================================
-- DROP UNUSED TABLES
-- Generated by Nerobot — 2026-08-10
-- ============================================================
-- Tabel-tabel ini sudah digantikan oleh tabel `_logs` yang baru
-- atau tabel lain yang sudah aktif dipakai di code.
--
-- PASTIKAN backup data dulu sebelum menjalankan script ini!
-- ============================================================

-- 1) Drop triggers dulu (agar drop table tidak error)
DROP TRIGGER IF EXISTS sholat_updated_at ON public.sholat;
DROP TRIGGER IF EXISTS quran_updated_at ON public.quran;
DROP TRIGGER IF EXISTS doa_updated_at ON public.doa;
DROP TRIGGER IF EXISTS syukur_updated_at ON public.syukur;
DROP TRIGGER IF EXISTS tidur_updated_at ON public.tidur;
DROP TRIGGER IF EXISTS masalah_updated_at ON public.masalah;
DROP TRIGGER IF EXISTS minum_air_updated_at ON public.minum_air;
DROP TRIGGER IF EXISTS pmo_updated_at ON public.pmo;
DROP TRIGGER IF EXISTS fun_queue_updated_at ON public.fun_queue;
DROP TRIGGER IF EXISTS improvement_backlog_updated_at ON public.improvement_backlog;

-- 2) Drop tabel legacy yang sudah digantikan
DROP TABLE IF EXISTS public.sholat;          -- digantikan prayer_logs
DROP TABLE IF EXISTS public.quran;           -- digantikan quran_logs
DROP TABLE IF EXISTS public.doa;             -- digantikan doa_logs
DROP TABLE IF EXISTS public.syukur;          -- digantikan syukur_logs
DROP TABLE IF EXISTS public.tidur;           -- digantikan tidur_logs
DROP TABLE IF EXISTS public.masalah;         -- digantikan masalah_logs
DROP TABLE IF EXISTS public.minum_air;       -- digantikan minum_air_logs
DROP TABLE IF EXISTS public.pmo;             -- digantikan pmo_logs
DROP TABLE IF EXISTS public.fun_queue;       -- digantikan kesenangan
DROP TABLE IF EXISTS public.improvement_backlog; -- digantikan saran_perbaikan

-- 3) Hapus dari publication realtime (jika terdaftar)
ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.sholat;
ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.quran;
ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.doa;
ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.syukur;
ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.tidur;
ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.masalah;
ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.minum_air;
ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.pmo;
ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.fun_queue;
ALTER PUBLICATION supabase_realtime DROP TABLE IF EXISTS public.improvement_backlog;

-- Selesai! 🐱
