-- ============================================================
-- DROP COLUMN: goal.kategori (kolom tampilan dihapus per permintaan user)
-- Generated by Nerobot — 2026-08-15
-- ============================================================

ALTER TABLE public.goal DROP COLUMN IF EXISTS kategori;

-- Selesai! 🐱
