-- ============================================================
-- CREATE TABLE: mental_block (kategori Pelajaran — mirip refleksi tanpa status)
-- Generated by Nerobot — 2026-08-19
--   tanggal: tanggal catatan (wajib)
--   masalah: isi mental block (wajib)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.mental_block (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    masalah TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mental_block_user_tanggal ON public.mental_block(user_id, tanggal);
ALTER TABLE public.mental_block ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own mental_block" ON public.mental_block;
CREATE POLICY "Users can CRUD own mental_block" ON public.mental_block
    FOR ALL USING (auth.uid() = user_id);

-- Trigger auto-update updated_at
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'mental_block' AND relnamespace = 'public'::regnamespace) THEN
        EXECUTE 'DROP TRIGGER IF EXISTS mental_block_updated_at ON public.mental_block';
        EXECUTE 'CREATE TRIGGER mental_block_updated_at BEFORE UPDATE ON public.mental_block FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    END IF;
END
$$;

-- Realtime: daftarkan ke publikasi
DO $$
BEGIN
    BEGIN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.mental_block';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END
$$;

-- Selesai! 🐱
