-- ============================================================
-- DROP COLUMN: goal.habit (fitur dihapus per permintaan user)
-- Generated by Nerobot — 2026-08-15
-- ============================================================

ALTER TABLE public.goal DROP COLUMN IF EXISTS habit;

-- Selesai! 🐱
