-- ============================================================
-- RENAME DATABASE TABLES
-- Generated by Nerobot — 2026-08-10
-- ============================================================
-- Peta rename:
--   doa_logs      → doa
--   kesenangan    → senang
--   masalah_logs  → refleksi
--   minum_air_logs → minum_air
--   pmo_logs      → pmo
--   prayer_logs   → sholat
--   quran_logs    → quran
--   syukur_logs   → syukur
--   tasks         → tugas
--   tidur_logs    → tidur
--
-- Catatan: tabel lama (sholat, quran, doa, syukur, tidur,
-- masalah, minum_air, pmo, kesenangan, saran_perbaikan,
-- fun_queue, improvement_backlog) sudah dihapus di migration
-- sebelumnya (20260810000002_drop_unused_tables.sql).
-- ============================================================

-- 1) Drop OLD tables yang sudah dihapus (idempotent)
DROP TABLE IF EXISTS public.sholat CASCADE;
DROP TABLE IF EXISTS public.quran CASCADE;
DROP TABLE IF EXISTS public.doa CASCADE;
DROP TABLE IF EXISTS public.syukur CASCADE;
DROP TABLE IF EXISTS public.tidur CASCADE;
DROP TABLE IF EXISTS public.masalah CASCADE;
DROP TABLE IF EXISTS public.minum_air CASCADE;
DROP TABLE IF EXISTS public.pmo CASCADE;
DROP TABLE IF EXISTS public.saran_perbaikan CASCADE;
DROP TABLE IF EXISTS public.fun_queue CASCADE;
DROP TABLE IF EXISTS public.improvement_backlog CASCADE;

-- 2) Rename tabel current → nama baru
ALTER TABLE IF EXISTS public.prayer_logs   RENAME TO sholat;
ALTER TABLE IF EXISTS public.quran_logs    RENAME TO quran;
ALTER TABLE IF EXISTS public.doa_logs      RENAME TO doa;
ALTER TABLE IF EXISTS public.syukur_logs   RENAME TO syukur;
ALTER TABLE IF EXISTS public.tidur_logs    RENAME TO tidur;
ALTER TABLE IF EXISTS public.masalah_logs  RENAME TO refleksi;
ALTER TABLE IF EXISTS public.minum_air_logs RENAME TO minum_air;
ALTER TABLE IF EXISTS public.pmo_logs      RENAME TO pmo;
ALTER TABLE IF EXISTS public.tasks         RENAME TO tugas;
ALTER TABLE IF EXISTS public.kesenangan    RENAME TO senang;

-- 3) Rename indexes agar konsisten dengan nama tabel baru
ALTER INDEX IF EXISTS idx_prayer_logs_user_tanggal    RENAME TO idx_sholat_user_tanggal;
ALTER INDEX IF EXISTS idx_quran_logs_user_tanggal     RENAME TO idx_quran_user_tanggal;
ALTER INDEX IF EXISTS idx_minum_air_logs_user_tanggal RENAME TO idx_minum_air_user_tanggal;
ALTER INDEX IF EXISTS idx_doa_logs_user_tanggal       RENAME TO idx_doa_user_tanggal;
ALTER INDEX IF EXISTS idx_syukur_logs_user_tanggal    RENAME TO idx_syukur_user_tanggal;
ALTER INDEX IF EXISTS idx_tidur_logs_user_tanggal     RENAME TO idx_tidur_user_tanggal;
ALTER INDEX IF EXISTS idx_masalah_logs_user_tanggal   RENAME TO idx_refleksi_user_tanggal;
ALTER INDEX IF EXISTS idx_pmo_logs_user_tanggal       RENAME TO idx_pmo_user_tanggal;

-- Selesai! 🐱
