-- ============================================================
-- MIGRATE: Pindah alasan begadang dari kolom `catatan` ke `alasan_tidak`
-- Tabel: tidur
-- Generated by Nerobot — 2026-08-10
-- ============================================================
-- Sebelumnya, alasan begadang disimpan di `catatan` dengan format:
--   "Begadang: Tak Bisa Tidur"
-- Sekarang pindah ke kolom khusus `alasan_tidak`.
-- ============================================================

-- 1) Pindahkan data existing: "Begadang: {reason}" → alasan_tidak = "{reason}"
UPDATE public.tidur
SET alasan_tidak = REPLACE(catatan, 'Begadang: ', '')
WHERE catatan LIKE 'Begadang: %';

-- 2) Bersihkan `catatan` yang berisi data begadang (sudah dipindah)
UPDATE public.tidur
SET catatan = NULL
WHERE catatan LIKE 'Begadang: %';
