-- ============================================================
-- Ubah opsi status refleksi: belum | sudah (drop proses/selesai)
-- Generated by Nerobot — 2026-08-16
-- Tab Refleksi & Tunda (Playlist) hanya pakai status Belum/Sudah.
-- Tabel refleksi sebelumnya punya CHECK status IN ('belum','proses','selesai').
-- Migration ini:
--   1) Normalisasi data lama: proses/selesai -> sudah
--   2) Drop constraint lama, add constraint baru (belum|sudah)
-- Idempoten & aman dijalankan berulang.
-- ============================================================

-- 1) Normalisasi data lama
UPDATE public.refleksi SET status = 'sudah' WHERE status IN ('proses', 'selesai');

-- 2) Drop constraint lama (nama umum: refleksi_status_check)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'refleksi_status_check'
  ) THEN
    ALTER TABLE public.refleksi DROP CONSTRAINT refleksi_status_check;
  END IF;
END $$;

-- 3) Add constraint baru
ALTER TABLE public.refleksi
  ADD CONSTRAINT refleksi_status_check CHECK (status IN ('belum', 'sudah'));

-- Selesai! 🐱
