-- ============================================================
-- CREATE TABLES: SWOT analysis (diri sendiri)
-- Generated by Nerobot — 2026-08-15
-- ============================================================

CREATE TABLE IF NOT EXISTS public.swot_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    kategori TEXT NOT NULL CHECK (kategori IN ('strength', 'weakness', 'opportunity', 'threat')),
    judul TEXT NOT NULL,
    prioritas TEXT NOT NULL DEFAULT 'sedang' CHECK (prioritas IN ('rendah', 'sedang', 'tinggi')),
    tren TEXT NOT NULL DEFAULT 'stagnan' CHECK (tren IN ('membaik', 'stagnan', 'memburuk')),
    status TEXT NOT NULL DEFAULT 'aktif' CHECK (status IN ('aktif', 'ditindak', 'selesai')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_swot_items_user ON public.swot_items(user_id, kategori);

CREATE TABLE IF NOT EXISTS public.swot_actions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    swot_item_id UUID REFERENCES public.swot_items(id) ON DELETE SET NULL,
    target TEXT NOT NULL,
    langkah_aksi TEXT,
    deadline DATE,
    progress INTEGER NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_swot_actions_user ON public.swot_actions(user_id);

CREATE TABLE IF NOT EXISTS public.swot_history (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    periode DATE NOT NULL DEFAULT CURRENT_DATE,
    snapshot JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_swot_history_user ON public.swot_history(user_id, periode);

-- RLS
ALTER TABLE public.swot_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swot_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.swot_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can CRUD own swot_items" ON public.swot_items;
CREATE POLICY "Users can CRUD own swot_items" ON public.swot_items
    FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can CRUD own swot_actions" ON public.swot_actions;
CREATE POLICY "Users can CRUD own swot_actions" ON public.swot_actions
    FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can CRUD own swot_history" ON public.swot_history;
CREATE POLICY "Users can CRUD own swot_history" ON public.swot_history
    FOR ALL USING (auth.uid() = user_id);

-- Trigger updated_at
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'swot_items_updated_at') THEN
        CREATE TRIGGER swot_items_updated_at BEFORE UPDATE ON public.swot_items
            FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'swot_actions_updated_at') THEN
        CREATE TRIGGER swot_actions_updated_at BEFORE UPDATE ON public.swot_actions
            FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
    END IF;
END
$$;

-- Realtime
DO $$
BEGIN
    BEGIN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.swot_items';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.swot_actions';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.swot_history';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END
$$;

-- Selesai! 🐱
