-- ============================================================
-- CREATE TABLE: goal_utama (goal yang di-promote ke posisi utama)
-- Setiap user punya MAKSIMAL 1 baris di sini (promote = pindah baris dari goal).
-- Generated by Nerobot — 2026-08-15
-- ============================================================

CREATE TABLE IF NOT EXISTS public.goal_utama (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal_set DATE NOT NULL,
    tanggal_deadline DATE NOT NULL,
    nama_goal TEXT NOT NULL,
    tempo TEXT,
    action_harian TEXT,
    langkah_aksi TEXT,
    group_id TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_goal_utama_user ON public.goal_utama(user_id);

ALTER TABLE public.goal_utama ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own goal_utama" ON public.goal_utama;
CREATE POLICY "Users can CRUD own goal_utama" ON public.goal_utama
    FOR ALL USING (auth.uid() = user_id);

-- Trigger updated_at
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'goal_utama_updated_at') THEN
        CREATE TRIGGER goal_utama_updated_at BEFORE UPDATE ON public.goal_utama
            FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
    END IF;
END
$$;

-- Realtime
DO $$
BEGIN
    BEGIN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.goal_utama';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END
$$;

-- ============================================================
-- PINDAH data existing: goal yang sudah is_utama=true -> goal_utama
-- (hanya 1 baris per user, ambil yang is_utama=true paling baru)
-- ============================================================
INSERT INTO public.goal_utama (user_id, tanggal_set, tanggal_deadline, nama_goal, tempo, action_harian, langkah_aksi, created_at, updated_at)
SELECT user_id, tanggal_set, tanggal_deadline, nama_goal, tempo, action_harian, langkah_aksi, created_at, updated_at
FROM public.goal g
WHERE g.is_utama = true
  AND NOT EXISTS (
    SELECT 1 FROM public.goal_utama gu WHERE gu.user_id = g.user_id
  );

-- Hapus goal yang sudah dipindah (is_utama=true) dari tabel goal biasa
DELETE FROM public.goal WHERE is_utama = true;

-- Selesai! 🐱
