-- ============================================================
-- MIGRASI: milestone bisa dicentang sendiri (is_completed)
-- Generated by Nerobot — 2026-09-11
--
-- Masalah: milestone yang belum punya step tidak bisa dicentang.
-- Solusi: kolom is_completed milik milestone sendiri, dengan
-- trigger sinkron otomatis dari status step-step di dalamnya.
--
-- CARA PAKAI (sekali saja):
-- 1. Buka dashboard Supabase project DayTrack
-- 2. Menu: SQL Editor → New query
-- 3. Copy seluruh file ini → paste → Run
-- ============================================================

-- 1) Kolom baru: status selesai milik milestone sendiri
ALTER TABLE public.goal_milestone
  ADD COLUMN IF NOT EXISTS is_completed BOOLEAN NOT NULL DEFAULT FALSE;

-- 2) Trigger: ketika SEMUA step dalam sebuah milestone selesai,
--    milestone otomatis ikut tercentang; kalau ada satu step dibuka,
--    centang milestone ikut terbuka.
CREATE OR REPLACE FUNCTION public.sync_milestone_completion()
RETURNS TRIGGER AS $$
DECLARE
  v_milestone UUID;
BEGIN
  -- Tentukan milestone dari row step yang berubah (INSERT/UPDATE/DELETE)
  v_milestone := COALESCE(NEW.milestone_id, OLD.milestone_id);
  IF v_milestone IS NULL THEN RETURN COALESCE(NEW, OLD); END IF;

  UPDATE public.goal_milestone m
  SET is_completed = (
    SELECT COALESCE(
      (SELECT bool_and(s.is_completed)
         FROM public.goal_step s
        WHERE s.milestone_id = v_milestone),
      FALSE)
  )
  WHERE m.id = v_milestone;

  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_sync_milestone_completion ON public.goal_step;
CREATE TRIGGER trg_sync_milestone_completion
  AFTER INSERT OR UPDATE OF is_completed OR DELETE
  ON public.goal_step
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_milestone_completion();

-- 3) Isi ulang status yang sudah ada (backfill) — jalankan sekali
UPDATE public.goal_milestone m
SET is_completed = COALESCE(
  (SELECT bool_and(s.is_completed) FROM public.goal_step s WHERE s.milestone_id = m.id),
  FALSE)
WHERE TRUE;

-- Selesai! 🐱 Setelah ini:
-- - Milestone yang belum punya step tetap bisa dicentang manual
--   (di kode app, centang manual tidak akan dibatasi step lagi)
-- - Milestone yang punya step: nilainya otomatis sinkron dari step-step
--   (app menampilkan gabungan: manual OR semua-step-selesai)
