-- ============================================================
-- ARUS KAS: tambah kolom dompet (sumber dana uang keluar)
-- Generated by Nerobot — 2026-08-13
-- ============================================================

-- dompet: hanya diisi saat kategori = 'uang_keluar'
--   kebutuhan  : dompet Kebutuhan (70%)
--   tabungan   : dompet Tabungan / Menabung Impian (10%)
--   self_reward: dompet Self Reward (10%)
--   sedekah    : dompet Sedekah (10%)
-- Untuk 'uang_masuk' kolom dibiarkan NULL.
ALTER TABLE public.arus_kas
  ADD COLUMN IF NOT EXISTS dompet TEXT;

-- Constraint opsional: batasi nilai + wajib saat uang_keluar
ALTER TABLE public.arus_kas
  DROP CONSTRAINT IF EXISTS arus_kas_dompet_check;

ALTER TABLE public.arus_kas
  ADD CONSTRAINT arus_kas_dompet_check
  CHECK (
    (kategori = 'uang_keluar' AND dompet IN ('kebutuhan', 'tabungan', 'self_reward', 'sedekah'))
    OR (kategori = 'uang_masuk' AND dompet IS NULL)
  );
