-- ============================================================
-- ADD COLUMN: goal.langkah_aksi (teks bebas, isian user)
-- Generated by Nerobot — 2026-08-15
-- ============================================================

ALTER TABLE public.goal ADD COLUMN IF NOT EXISTS langkah_aksi TEXT;

-- Selesai! 🐱
