-- ============================================================
-- SWOT: izinkan kategori kombinasi (so/wo/st/wt) di swot_items
-- Generated by Nerobot — 2026-08-17
--   Card Kombinasi Logika pakai item list (bukan kolom teks),
--   sehingga butuh 4 nilai kategori baru yang reusable dengan S/W/O/T.
-- ============================================================

DO $$
DECLARE
  cname text;
BEGIN
  SELECT conname INTO cname
  FROM pg_constraint c
  JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
  WHERE c.conrelid = 'public.swot_items'::regclass
    AND a.attname = 'kategori'
    AND c.contype = 'c'
  LIMIT 1;
  IF cname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.swot_items DROP CONSTRAINT %I', cname);
  END IF;
END $$;

ALTER TABLE public.swot_items
  ADD CONSTRAINT swot_items_kategori_check
  CHECK (kategori IN ('strength','weakness','opportunity','threat','so','wo','st','wt'));

-- Selesai! 🐱
