-- ============================================================
-- ALTER TABLE: catatan — tambah kolom label (kategori)
-- Generated by Nerobot — 2026-08-16
-- ============================================================

ALTER TABLE public.catatan
  ADD COLUMN IF NOT EXISTS label TEXT NOT NULL DEFAULT '';

-- Selesai! 🐱
