-- ============================================================
-- SWOT: tambah kolom Kombinasi Logika (SO/WO/ST/WT) per analisis
-- Generated by Nerobot — 2026-08-17
--   4 kolom TEXT di swot_topics (bisa diisi teks bebas)
-- ============================================================

ALTER TABLE public.swot_topics
    ADD COLUMN IF NOT EXISTS so_note TEXT,
    ADD COLUMN IF NOT EXISTS wo_note TEXT,
    ADD COLUMN IF NOT EXISTS st_note TEXT,
    ADD COLUMN IF NOT EXISTS wt_note TEXT;

-- Selesai! 🐱
