-- ============================================================
-- CREATE TABLE: catatan (kategori Pelajaran — sticky note)
-- Generated by Nerobot — 2026-08-16
--   judul: judul catatan (wajib)
--   isi  : isi catatan (wajib)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.catatan (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    judul TEXT NOT NULL,
    isi TEXT NOT NULL,
    label TEXT NOT NULL DEFAULT '',
    warna TEXT NOT NULL DEFAULT 'yellow'
        CHECK (warna IN ('yellow', 'green', 'blue', 'pink', 'orange')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_catatan_user_created ON public.catatan(user_id, created_at);
ALTER TABLE public.catatan ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own catatan" ON public.catatan;
CREATE POLICY "Users can CRUD own catatan" ON public.catatan
    FOR ALL USING (auth.uid() = user_id);

-- Trigger auto-update updated_at
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'catatan' AND relnamespace = 'public'::regnamespace) THEN
        EXECUTE 'DROP TRIGGER IF EXISTS catatan_updated_at ON public.catatan';
        EXECUTE 'CREATE TRIGGER catatan_updated_at BEFORE UPDATE ON public.catatan FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    END IF;
END
$$;

-- Realtime: daftarkan ke publikasi
DO $$
BEGIN
    BEGIN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.catatan';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END
$$;

-- Selesai! 🐱
