-- ============================================================
-- BACKFILL: data arus_kas lama (uang_keluar tanpa dompet)
-- Generated by Nerobot — 2026-08-13
-- ============================================================
-- Sebelum fitur dompet ada, uang keluar disimpan dengan dompet = NULL.
-- Agar card alokasi (Opsi A: pengurangan langsung) konsisten dengan
-- pengeluaran historis, defaultkan dompet lama ke 'kebutuhan'.
UPDATE public.arus_kas
SET dompet = 'kebutuhan'
WHERE kategori = 'uang_keluar'
  AND dompet IS NULL;
