-- ============================================================
-- CREATE TABLE: sedekah (tab Sedekah — kategori Hoki)
-- Generated by Nerobot — 2026-08-11
-- Struktur sama dengan tabel syukur (status harian + alasan_tidak)
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- SEDekAH
-- ============================================
CREATE TABLE IF NOT EXISTS public.sedekah (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    status TEXT DEFAULT 'belum',
    alasan_tidak TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, tanggal)
);

CREATE INDEX IF NOT EXISTS idx_sedekah_user_date ON public.sedekah(user_id, tanggal);
ALTER TABLE public.sedekah ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own sedekah" ON public.sedekah;
CREATE POLICY "Users can CRUD own sedekah" ON public.sedekah
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- TRIGGER: auto-update updated_at
-- ============================================
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'sedekah' AND relnamespace = 'public'::regnamespace) THEN
        EXECUTE 'DROP TRIGGER IF EXISTS sedekah_updated_at ON public.sedekah';
        EXECUTE 'CREATE TRIGGER sedekah_updated_at BEFORE UPDATE ON public.sedekah FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    END IF;
END
$$;

-- ============================================
-- REALTIME: daftarkan tabel ke publikasi
-- ============================================
DO $$
BEGIN
    BEGIN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.sedekah';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END
$$;

-- Selesai! 🐱
