-- ============================================================
-- SWOT: kolom topic_id di swot_actions (scope action per analisis)
-- Generated by Nerobot — 2026-08-16
-- ============================================================

ALTER TABLE public.swot_actions
    ADD COLUMN IF NOT EXISTS topic_id UUID REFERENCES public.swot_topics(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_swot_actions_topic ON public.swot_actions(topic_id);

-- Backfill: action yg belum punya topic_id -> ambil dari item terkait (jika ada)
UPDATE public.swot_actions a
SET topic_id = i.topic_id
FROM public.swot_items i
WHERE a.topic_id IS NULL
  AND a.swot_item_id IS NOT NULL
  AND a.swot_item_id = i.id;

-- Selesai! 🐱
