-- ============================================================
-- CREATE TABLE: makan (kategori Kesehatan)
-- Generated by Nerobot — 2026-08-31
-- ============================================================
-- Pencatatan jam makan (pagi/siang/malam).
-- Jeda antar makan dihitung di client (tidak disimpan).

CREATE TABLE IF NOT EXISTS public.makan (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    makan_pagi TIME,
    makan_siang TIME,
    makan_malam TIME,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_makan_user_date ON public.makan(user_id, tanggal);
ALTER TABLE public.makan ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own makan" ON public.makan;
CREATE POLICY "Users can CRUD own makan" ON public.makan
    FOR ALL USING (auth.uid() = user_id);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'makan' AND relnamespace = 'public'::regnamespace) THEN
        EXECUTE 'DROP TRIGGER IF EXISTS makan_updated_at ON public.makan';
        EXECUTE 'CREATE TRIGGER makan_updated_at BEFORE UPDATE ON public.makan FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    END IF;
END
$$;

DO $$
BEGIN
    BEGIN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.makan';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END
$$;
