-- ============================================================
-- DROP UNUSED TABLES
-- Generated by Nerobot — 2026-08-10
-- ============================================================
-- Tabel-tabel ini sudah digantikan oleh tabel `_logs` yang baru.
-- PASTIKAN backup data dulu sebelum menjalankan script ini!
-- ============================================================

-- 1) Hapus dari publication realtime jika ada
DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'sholat', 'quran', 'doa', 'syukur', 'tidur',
    'masalah', 'minum_air', 'pmo', 'fun_queue', 'improvement_backlog'
  ] LOOP
    IF EXISTS (
      SELECT 1 FROM pg_publication_rel pr
      JOIN pg_publication p ON p.oid = pr.prpubid
      JOIN pg_class c ON c.oid = pr.prrelid
      WHERE p.pubname = 'supabase_realtime' AND c.relname = t
    ) THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime DROP TABLE public.%I', t);
    END IF;
  END LOOP;
END
$$;

-- 2) Drop triggers + tables sekaligus (skip jika tabel tidak ada)
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT unnest(ARRAY[
      'sholat', 'quran', 'doa', 'syukur', 'tidur',
      'masalah', 'minum_air', 'pmo', 'fun_queue', 'improvement_backlog'
    ]) AS tbl
  LOOP
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = r.tbl AND relnamespace = 'public'::regnamespace) THEN
      -- Drop trigger dulu
      EXECUTE format('DROP TRIGGER IF EXISTS %I_updated_at ON public.%I', r.tbl, r.tbl);
      -- Drop table (cascade untuk bersihkan dependensi)
      EXECUTE format('DROP TABLE IF EXISTS public.%I CASCADE', r.tbl);
      RAISE NOTICE 'Dropped table: %', r.tbl;
    ELSE
      RAISE NOTICE 'Skipped (not found): %', r.tbl;
    END IF;
  END LOOP;
END
$$;

-- Selesai! 🐱
