-- ============================================================
-- ARUS KAS: tambah dompet 'paylater' (utang konsumtif)
-- Generated by Scriva — 2026-08-19
-- ============================================================
-- paylater = belanja pakai paylater (utang). Bukan bagian alokasi
-- 70/10/10/10 (karena itu kewajiban, bukan penghasilan).
-- Hanya valid untuk kategori = 'uang_keluar'.

COMMENT ON COLUMN public.arus_kas.dompet IS
  'Sumber dana uang_keluar: kebutuhan | tabungan | self_reward | sedekah | paylater. NULL untuk uang_masuk.';

ALTER TABLE public.arus_kas
  DROP CONSTRAINT IF EXISTS arus_kas_dompet_check;

ALTER TABLE public.arus_kas
  ADD CONSTRAINT arus_kas_dompet_check
  CHECK (
    (kategori = 'uang_keluar' AND dompet IN ('kebutuhan', 'tabungan', 'self_reward', 'sedekah', 'paylater'))
    OR (kategori = 'uang_masuk' AND dompet IS NULL)
  );
