-- ============================================================
-- Allow tasks to be saved WITHOUT a date (for "ide yang belum matang")
-- Generated by Nerobot — 2026-08-12
-- Nama tabel: tugas (bukan tasks — sudah di-rename di 20260810000003_rename_tables.sql)
-- ============================================================

ALTER TABLE public.tugas ALTER COLUMN tanggal DROP NOT NULL;

-- Selesai! 🐱
