-- ============================================================
-- Tabel bank_ide — pisahkan ide dari tabel tugas
-- Generated by Nerobot — 2026-09-10
-- Idempoten & aman dijalankan berulang.
-- ============================================================

-- 0) Ekstensi uuid (biasanya sudah ada, amankan)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1) Buat tabel bank_ide
CREATE TABLE IF NOT EXISTS public.bank_ide (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    catatan TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bank_ide_user ON public.bank_ide(user_id);
CREATE INDEX IF NOT EXISTS idx_bank_ide_user_created ON public.bank_ide(user_id, created_at DESC);

-- 2) RLS
ALTER TABLE public.bank_ide ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own bank_ide" ON public.bank_ide;
CREATE POLICY "Users can CRUD own bank_ide" ON public.bank_ide
    FOR ALL USING (auth.uid() = user_id);

-- 3) Trigger updated_at (function sudah ada project-wide)
DROP TRIGGER IF EXISTS bank_ide_updated_at ON public.bank_ide;
CREATE TRIGGER bank_ide_updated_at BEFORE UPDATE ON public.bank_ide
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- 4) Masukkan ide lama dari tugas (status = 'ide') ke bank_ide — hanya jika belum dipindah
--    (idempoten: skip kalau bank_ide sudah punya catatan sama untuk user yg sama)
INSERT INTO public.bank_ide (user_id, catatan, created_at, updated_at)
SELECT t.user_id, t.nama, t.created_at, t.updated_at
FROM public.tugas t
WHERE t.status = 'ide'
  AND NOT EXISTS (
    SELECT 1 FROM public.bank_ide b
    WHERE b.user_id = t.user_id AND b.catatan = t.nama
  );

-- 5) Hapus ide lama dari tabel tugas (sudah dipindah ke bank_ide)
DELETE FROM public.tugas WHERE status = 'ide';

-- 6) Lepas nilai 'ide' dari constraint status tugas
DO $$
DECLARE
  v_conname text;
BEGIN
  SELECT conname INTO v_conname
  FROM pg_constraint
  WHERE conrelid = 'public.tugas'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%status%';

  IF v_conname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.tugas DROP CONSTRAINT %I', v_conname);
  END IF;
END $$;

ALTER TABLE public.tugas
  ADD CONSTRAINT tugas_status_check CHECK (status IN ('belum', 'proses', 'selesai'));

-- 7) Daftarkan bank_ide ke realtime publication
DO $$
BEGIN
  BEGIN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.bank_ide';
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END $$;

-- Selesai! 🐱
