-- ============================================================
-- RENAME tabel senang -> playlist
-- Generated by Nerobot — 2026-08-16
-- Tujuan: menyelaraskan nama tabel database dengan nama tab UI.
--   Tab "Kesenangan" sudah diubah namanya menjadi "Playlist" di sidebar,
--   sehingga tabel `senang` (hasil rename dari `kesenangan`) diganti
--   namanya menjadi `playlist` agar konsisten dengan UI.
--
-- Kolom yang dipakai UI Playlist (tidak berubah):
--   kesenangan (teks -> kolom "Link Video"), status ('belum'|'sudah')
--   tanggal/hari dipakai untuk sorting internal (tetap dipertahankan).
--
-- Idempotent: aman dijalankan berulang.
-- ============================================================

-- 1) Rename tabel
ALTER TABLE IF EXISTS public.senang RENAME TO playlist;

-- 2) Rename index agar konsisten (nama lama: idx_kesenangan_user_date)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_indexes WHERE indexname = 'idx_kesenangan_user_date'
  ) THEN
    ALTER INDEX IF EXISTS idx_kesenangan_user_date RENAME TO idx_playlist_user_date;
  END IF;
END $$;

-- 3) Realtime publication: pastikan playlist terdaftar (abaikan kalau sudah)
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.playlist;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END $$;

-- Selesai! 🐱
