-- ============================================================
-- MAKAN: tambah kolom isi makanan (apa yang dimakan)
-- Generated by Nerobot — 2026-08-31
-- ============================================================

ALTER TABLE public.makan
  ADD COLUMN IF NOT EXISTS makan_pagi_isi TEXT,
  ADD COLUMN IF NOT EXISTS makan_siang_isi TEXT,
  ADD COLUMN IF NOT EXISTS makan_malam_isi TEXT;
