-- ============================================================
-- ARUS KAS: tambah kolom klasifikasi (kategori rinci uang keluar)
-- Generated by Nerobot — 2026-08-31
-- ============================================================
-- klasifikasi: kategori rinci untuk kategori = 'uang_keluar'
--   (beli_makanan, cemilan, self_reward, sedekah, laundry, bayar_kos,
--    ojek, jajan, pencuci_muka, sabun, galon_air, pulsa, gas_kompor,
--    pasta_gigi, sembako). NULL untuk uang_masuk.
-- Opsi hanya boleh satu (single select).

ALTER TABLE public.arus_kas
  ADD COLUMN IF NOT EXISTS klasifikasi TEXT;

ALTER TABLE public.arus_kas
  DROP CONSTRAINT IF EXISTS arus_kas_klasifikasi_check;

ALTER TABLE public.arus_kas
  ADD CONSTRAINT arus_kas_klasifikasi_check
  CHECK (
    (kategori = 'uang_masuk' AND klasifikasi IS NULL)
    OR (kategori = 'uang_keluar'
        AND (klasifikasi IS NULL
             OR klasifikasi IN (
               'beli_makanan', 'cemilan', 'self_reward', 'sedekah', 'laundry',
               'bayar_kos', 'ojek', 'jajan', 'pencuci_muka', 'sabun',
               'galon_air', 'pulsa', 'gas_kompor', 'pasta_gigi', 'sembako'
             )))
  );

COMMENT ON COLUMN public.arus_kas.klasifikasi IS
  'Kategori rinci uang_keluar: beli_makanan | cemilan | self_reward | sedekah | laundry | bayar_kos | ojek | jajan | pencuci_muka | sabun | galon_air | pulsa | gas_kompor | pasta_gigi | sembako. NULL untuk uang_masuk.';
