-- ============================================================
-- MAKAN: tambah kolom keterangan (catatan bebas)
-- Generated by Nerobot — 2026-08-31
-- ============================================================

ALTER TABLE public.makan
  ADD COLUMN IF NOT EXISTS keterangan TEXT;
