-- ============================================================
-- ADD COLUMN: goal.tempo (teks bebas, isian user)
-- Generated by Nerobot — 2026-08-15
-- ============================================================

ALTER TABLE public.goal ADD COLUMN IF NOT EXISTS tempo TEXT;

-- Selesai! 🐱
