-- ============================================================
-- CREATE TABLE: arus_kas + keranjang (kategori Keuangan)
-- Generated by Nerobot — 2026-08-13
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- ARUS KAS
--   kategori: 'uang_masuk' | 'uang_keluar'
--   nominal: angka (Rupiah)
--   alasan : sumber (masuk) / tujuan belanja (keluar)
-- ============================================
CREATE TABLE IF NOT EXISTS public.arus_kas (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    kategori TEXT NOT NULL CHECK (kategori IN ('uang_masuk', 'uang_keluar')),
    nominal INTEGER NOT NULL DEFAULT 0,
    alasan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_arus_kas_user_date ON public.arus_kas(user_id, tanggal);
ALTER TABLE public.arus_kas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own arus_kas" ON public.arus_kas;
CREATE POLICY "Users can CRUD own arus_kas" ON public.arus_kas
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- KERANJANG (list belanjaan yang akan dibeli)
--   status: 'belum' | 'sudah'
--   saat status -> 'sudah': baris dihapus & pindah ke arus_kas (uang_keluar)
--     nominal = harga, alasan = nama_barang
-- ============================================
CREATE TABLE IF NOT EXISTS public.keranjang (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    nama_barang TEXT NOT NULL,
    harga INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'belum' CHECK (status IN ('belum', 'sudah')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_keranjang_user_date ON public.keranjang(user_id, tanggal);
ALTER TABLE public.keranjang ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own keranjang" ON public.keranjang;
CREATE POLICY "Users can CRUD own keranjang" ON public.keranjang
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- TRIGGER: auto-update updated_at
-- ============================================
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'arus_kas' AND relnamespace = 'public'::regnamespace) THEN
        EXECUTE 'DROP TRIGGER IF EXISTS arus_kas_updated_at ON public.arus_kas';
        EXECUTE 'CREATE TRIGGER arus_kas_updated_at BEFORE UPDATE ON public.arus_kas FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    END IF;
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'keranjang' AND relnamespace = 'public'::regnamespace) THEN
        EXECUTE 'DROP TRIGGER IF EXISTS keranjang_updated_at ON public.keranjang';
        EXECUTE 'CREATE TRIGGER keranjang_updated_at BEFORE UPDATE ON public.keranjang FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    END IF;
END
$$;

-- ============================================
-- REALTIME: daftarkan tabel ke publikasi
-- ============================================
DO $$
BEGIN
    BEGIN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.arus_kas';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.keranjang';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END
$$;

-- Selesai! 🐱
