-- ============================================================
-- KERANJANG: tambah kolom dompet (sumber dana saat "Sudah" dipencet)
-- Generated by Nerobot — 2026-08-13
-- ============================================================

-- dompet: dipilih saat input barang, dipakai saat pindah ke arus_kas
--   kebutuhan | tabungan | self_reward | sedekah
ALTER TABLE public.keranjang
  ADD COLUMN IF NOT EXISTS dompet TEXT DEFAULT 'kebutuhan';

ALTER TABLE public.keranjang
  DROP CONSTRAINT IF EXISTS keranjang_dompet_check;

ALTER TABLE public.keranjang
  ADD CONSTRAINT keranjang_dompet_check
  CHECK (dompet IN ('kebutuhan', 'tabungan', 'self_reward', 'sedekah'));
