-- ============================================================
-- CREATE TABLE: goal (target barang belanjaan)
-- Generated by Nerobot — 2026-08-15
-- ============================================================

CREATE TABLE IF NOT EXISTS public.goal (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal_set DATE NOT NULL,
    tanggal_deadline DATE NOT NULL,
    nama_goal TEXT NOT NULL,
    proyeksi_harga INTEGER NOT NULL DEFAULT 0,
    kategori TEXT NOT NULL DEFAULT 'kebutuhan' CHECK (kategori IN ('kebutuhan', 'tabungan', 'self_reward', 'sedekah')),
    action_harian TEXT,
    habit TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_goal_user_date ON public.goal(user_id, tanggal_set);
ALTER TABLE public.goal ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own goal" ON public.goal;
CREATE POLICY "Users can CRUD own goal" ON public.goal
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- TRIGGER: auto-update updated_at
-- ============================================
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'goal' AND relnamespace = 'public'::regnamespace) THEN
        EXECUTE 'DROP TRIGGER IF EXISTS goal_updated_at ON public.goal';
        EXECUTE 'CREATE TRIGGER goal_updated_at BEFORE UPDATE ON public.goal FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()';
    END IF;
END
$$;

-- ============================================
-- REALTIME: daftarkan tabel ke publikasi
-- ============================================
DO $$
BEGIN
    BEGIN
        EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.goal';
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
END
$$;

-- Selesai! 🐱
