-- ============================================================
-- Tambah status 'ide' ke tabel tugas
-- Generated by Nerobot — 2026-08-28
-- Tab "Bank Ide" (kategori Tugas) = tugas dengan status 'ide'.
-- Idempoten & aman dijalankan berulang.
-- ============================================================

-- 1) Cari nama constraint status tabel tugas (biasanya tugas_status_check)
--    lalu drop + buat ulang dengan opsi 'ide'.
DO $$
DECLARE
  v_conname text;
BEGIN
  SELECT conname INTO v_conname
  FROM pg_constraint
  WHERE conrelid = 'public.tugas'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%status%';

  IF v_conname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.tugas DROP CONSTRAINT %I', v_conname);
  END IF;
END $$;

-- 2) Constraint baru: belum | proses | selesai | ide
ALTER TABLE public.tugas
  ADD CONSTRAINT tugas_status_check CHECK (status IN ('belum', 'proses', 'selesai', 'ide'));

-- Selesai! 🐱
