-- ============================================================
-- CREATE MISSING TABLES
-- Generated by Nerobot — 2026-08-10
-- ============================================================
-- Hanya tabel yang BELUM ADA di database.
-- Tabel tugas, refleksi, senang sudah ada — tidak perlu dibuat ulang.
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- 1. SHOLAT (renamed from prayer_logs)
-- ============================================
CREATE TABLE IF NOT EXISTS public.sholat (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    status TEXT DEFAULT 'belum',
    sholat_subuh BOOLEAN DEFAULT FALSE,
    sholat_dhuha BOOLEAN DEFAULT FALSE,
    sholat_dzuhur BOOLEAN DEFAULT FALSE,
    sholat_ashar BOOLEAN DEFAULT FALSE,
    sholat_maghrib BOOLEAN DEFAULT FALSE,
    sholat_isya BOOLEAN DEFAULT FALSE,
    alasan_subuh TEXT,
    alasan_dhuha TEXT,
    alasan_dzuhur TEXT,
    alasan_ashar TEXT,
    alasan_maghrib TEXT,
    alasan_isya TEXT,
    kualitas_subuh SMALLINT DEFAULT NULL CHECK (kualitas_subuh IN (1, 2, 3, 4, 5)),
    kualitas_dhuha SMALLINT DEFAULT NULL CHECK (kualitas_dhuha IN (1, 2, 3, 4, 5)),
    kualitas_dzuhur SMALLINT DEFAULT NULL CHECK (kualitas_dzuhur IN (1, 2, 3, 4, 5)),
    kualitas_ashar SMALLINT DEFAULT NULL CHECK (kualitas_ashar IN (1, 2, 3, 4, 5)),
    kualitas_maghrib SMALLINT DEFAULT NULL CHECK (kualitas_maghrib IN (1, 2, 3, 4, 5)),
    kualitas_isya SMALLINT DEFAULT NULL CHECK (kualitas_isya IN (1, 2, 3, 4, 5)),
    refleksi TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, tanggal)
);

CREATE INDEX IF NOT EXISTS idx_sholat_user_date ON public.sholat(user_id, tanggal);
ALTER TABLE public.sholat ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own sholat" ON public.sholat;
CREATE POLICY "Users can CRUD own sholat" ON public.sholat
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- 2. QURAN (renamed from quran_logs)
-- ============================================
CREATE TABLE IF NOT EXISTS public.quran (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    waktu_baca TEXT NOT NULL,
    surat TEXT,
    juz SMALLINT,
    halaman_mulai SMALLINT,
    halaman_selesai SMALLINT,
    jumlah_halaman SMALLINT,
    catatan TEXT,
    kualitas SMALLINT CHECK (kualitas >= 1 AND kualitas <= 5),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_quran_user_date ON public.quran(user_id, tanggal);
ALTER TABLE public.quran ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own quran" ON public.quran;
CREATE POLICY "Users can CRUD own quran" ON public.quran
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- 3. DOA (renamed from doa_logs)
-- ============================================
CREATE TABLE IF NOT EXISTS public.doa (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    status TEXT DEFAULT 'belum',
    untuk_siapa TEXT,
    keterangan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_doa_user_date ON public.doa(user_id, tanggal);
ALTER TABLE public.doa ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own doa" ON public.doa;
CREATE POLICY "Users can CRUD own doa" ON public.doa
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- 4. SYUKUR (renamed from syukur_logs)
-- ============================================
CREATE TABLE IF NOT EXISTS public.syukur (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    status TEXT DEFAULT 'belum',
    isi_syukur TEXT,
    kategori TEXT,
    catatan TEXT,
    alasan_tidak TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_syukur_user_date ON public.syukur(user_id, tanggal);
ALTER TABLE public.syukur ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own syukur" ON public.syukur;
CREATE POLICY "Users can CRUD own syukur" ON public.syukur
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- 5. TIDUR (renamed from tidur_logs)
-- ============================================
CREATE TABLE IF NOT EXISTS public.tidur (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    status TEXT DEFAULT 'tepat',
    jam_tidur TIME,
    jam_bangun TIME,
    durasi_jam NUMERIC,
    kualitas SMALLINT,
    catatan TEXT,
    alasan_tidak TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tidur_user_date ON public.tidur(user_id, tanggal);
ALTER TABLE public.tidur ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own tidur" ON public.tidur;
CREATE POLICY "Users can CRUD own tidur" ON public.tidur
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- 6. MINUM_AIR (renamed from minum_air_logs)
-- ============================================
CREATE TABLE IF NOT EXISTS public.minum_air (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    waktu_baca TEXT NOT NULL,
    jumlah_ml INTEGER DEFAULT 250,
    catatan TEXT,
    status TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_minum_air_user_date ON public.minum_air(user_id, tanggal);
ALTER TABLE public.minum_air ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own minum_air" ON public.minum_air;
CREATE POLICY "Users can CRUD own minum_air" ON public.minum_air
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- 7. PMO (renamed from pmo_logs)
-- ============================================
CREATE TABLE IF NOT EXISTS public.pmo (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    hari_ke INTEGER NOT NULL,
    status TEXT NOT NULL,
    trigger TEXT,
    strategi TEXT,
    catatan TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pmo_user_date ON public.pmo(user_id, tanggal);
ALTER TABLE public.pmo ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own pmo" ON public.pmo;
CREATE POLICY "Users can CRUD own pmo" ON public.pmo
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- 8. SARAN_PERBAIKAN
-- ============================================
CREATE TABLE IF NOT EXISTS public.saran_perbaikan (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tanggal DATE NOT NULL,
    hari TEXT NOT NULL,
    saran TEXT NOT NULL,
    keterangan TEXT,
    status TEXT CHECK (status IN ('belum', 'proses', 'selesai')) DEFAULT 'belum',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_saran_perbaikan_user_date ON public.saran_perbaikan(user_id, tanggal);
ALTER TABLE public.saran_perbaikan ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own saran_perbaikan" ON public.saran_perbaikan;
CREATE POLICY "Users can CRUD own saran_perbaikan" ON public.saran_perbaikan
    FOR ALL USING (auth.uid() = user_id);

-- ============================================
-- TRIGGERS: auto-update updated_at
-- ============================================
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOREACH tbl IN ARRAY ARRAY['sholat', 'quran', 'doa', 'syukur', 'tidur', 'minum_air', 'pmo'] LOOP
        IF EXISTS (SELECT 1 FROM pg_class WHERE relname = tbl AND relnamespace = 'public'::regnamespace) THEN
            EXECUTE format('DROP TRIGGER IF EXISTS %I_updated_at ON public.%I', tbl, tbl);
            EXECUTE format('CREATE TRIGGER %I_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at()', tbl, tbl);
        END IF;
    END LOOP;
END
$$;

-- ============================================
-- REALTIME: daftarkan tabel ke publikasi
-- ============================================
DO $$
DECLARE
    tbl TEXT;
BEGIN
    FOREACH tbl IN ARRAY ARRAY['sholat', 'quran', 'doa', 'syukur', 'tidur', 'minum_air', 'pmo', 'saran_perbaikan'] LOOP
        BEGIN
            EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', tbl);
        EXCEPTION WHEN duplicate_object THEN NULL;
        END;
    END LOOP;
END
$$;

-- ============================================
-- PERMISSIONS
-- ============================================
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO postgres, authenticated, service_role;

-- Selesai! 🐱
